[package]
name = "androidfs"
version = "0.1.0"
edition = "2021"

[workspace]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
futuresdr = { path = "../..", features = ["vulkan"] }
jni = { version = "0.19" }
rand = "0.8.0"
