[package]
name = "perf-burn"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
anyhow = "1.0"
burn = { version = "0.19", features = [
  "cuda",
  "vulkan",
  "webgpu",
  "autotune",
  "fusion",
] }
burn-cubecl = "0.19"
burn-fusion = "0.19"
burn-wgpu = "0.19"
bytemuck = "1.24"
cubecl = "0.8"
cubecl-wgpu = "0.8"
futuresdr = { path = "../..", features = ["burn", "seify"] }
futuresdr-burn = { path = "../../examples/burn" }
ndarray = "0.16"
tracing = { version = "0.1", features = ["release_max_level_off"] }
