[package]
name = "vulkan"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.1.0"
futuresdr = { path = "../..", features = ["vulkan"] }
rand = "0.8.0"

[[bin]]
name = "vulkan"
path = "vulkan.rs"
