[package]
name = "cw"
version = "0.0.1"
edition = "2021"

[workspace]

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "listen-cw"
path = "src/bin/listen_cw.rs"

[dependencies]
futuresdr = { path = "../..", features = ["audio"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap = { version = "4.0.19", features = ["derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
wasm-bindgen = "0.2.79"
wasm-bindgen-futures = "0.4.29"
