[package]
name = "zeromq"
version = "0.1.0"
edition = "2018"

[dependencies]
futuresdr = { path = "../..", default-features = false, features=["zeromq"] }
anyhow = "1.0.38"

[[bin]]
name = "zmq-receiver"
path = "zmq_receiver.rs"

[[bin]]
name = "zmq-emitter"
path = "zmq_emitter.rs"
