[package]
name = "zeromq"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
futuresdr = { path = "../..", features = ["zeromq"] }

[[bin]]
name = "zmq-receiver"
path = "zmq_receiver.rs"

[[bin]]
name = "zmq-emitter"
path = "zmq_emitter.rs"
