[package]
name = "wlan"
version = "0.1.0"
edition = "2021"
default-run = "loopback"

[workspace]

[[bin]]
name = "rx"
path = "src/bin/rx.rs"

[[bin]]
name = "loopback"
path = "src/bin/loopback.rs"

[[bin]]
name = "tx"
path = "src/bin/tx.rs"

[[bin]]
name = "aaronia"
path = "src/bin/aaronia.rs"
required-features = ["aaronia"]

[features]
default = []
aaronia = ["futuresdr/aaronia"]

[dependencies]
clap = { version = "4.0.19", features = ["derive"] }
crc32fast = "1.3.2"
futuresdr = { path = "../..", features = ["soapy"] }
rand = "0.8.5"
rand_distr = "0.4.3"
