[package]
name = "fm-receiver"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
clap = { version = "4.0.19", features = ["derive"] }
futuresdr = { path = "../..", features=["soapy", "audio"] }
futuredsp = { path = "../../futuredsp" }
