[book]
title = "FutureSDR Documentation"
authors = ["Bastian Bloessl"]
language = "en"
src = "src"

[rust]
edition = "2024"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/futuresdr/futuresdr"
edit-url-template = "https://github.com/futuresdr/futuresdr/edit/main/book/{path}"
site-url = "/learn/"
cname = "futuresdr.org"

[output.html.playground]
runnable = false

